engines:
  eslint:
    enabled: true
  csslint:
    enabled: true
  duplication:
    enabled: true
    config:
        languages:
        - javascript
exclude_paths:
  - "demo/"
  - "dist/"
  - "docs/"
  - "e2e/"
  - "node_modules/"
  - "tools/"
  - "src/assets/"
ratings:
   paths:
   - "src/**/**.ts"
